language: node_js
node_js:
  - "0.12"
before_install: npm install -g grunt-cli
install: npm install
before_script: grunt build
deploy:
  provider: heroku
  api_key: "0239493c-3605-4ae6-b9b9-91b571366504"
  app: sudokuz
  run:
      - restart

